### ISSUE TITLE
unable to run SVFX

### ISSUE THREAD

**Issue by kleinertp** [gersteinlab/SVFX#1]
Hello, I tried to run SVFX and realized that not all dependencies are provided in the list of dependencies. Some are probably custom made scripts like "tools" that I couldn't obtain elsewhere.
Further, the generate_feature_matrix.py script has bad formatting.
Thank you for your help.

**Comment by SKY2014** [comment]
Hi, Thanks for your interest in SVFX. Please check the updated version of the code, which should help address the issue raised by you. Please let us know if you still encounter any problems.
