### ISSUE TITLE
Problem setting conda environment

### ISSUE THREAD

**Issue by frequena** [gersteinlab/SVFX#6]
Hello, I'm unable to create the conda environment.

Once I cloned the repository, I ran the following code:

`conda env create -f SVFXenv.yml && conda activate SVFXenv`

and I get this error:
```

Solving environment: failed

ResolvePackageNotFound:
  - openssl==1.1.1g=h0b31af3_0
  - llvm-openmp==9.0.1=h28b9765_2
  - ncurses==6.1=h0a44026_1002
  - tk==8.6.10=hbbe82c9_0
  - libopenblas==0.3.9=h3d69b6c_0
  - scipy==1.4.1=py37h82752d6_0
  - pybigwig==0.3.17=py37haec6b85_0
  - libedit==3.1.20170329=hcfe32e1_1001
  - libssh2==1.8.2=hcdc9a53_2
  - libgfortran==4.0.0=2
  - readline==8.0=hcfe32e1_0
  - pandas==1.0.3=py37h94625e5_0
  - sqlite==3.30.1=h93121df_0
  - python==3.7.6=hfa4aa89_4_cpython
  - libffi==3.2.1=h4a8c4bd_1007
  - xz==5.2.4=h0b31af3_1002
  - libcurl==7.68.0=h709d2b2_0
  - krb5==1.16.4=h1752a42_0
  - zlib==1.2.11=h0b31af3_1006
```

Thank you!!

**Comment by jagathv** [comment]
Hi, thank you for letting us know! What platform are you running this on (MacOS, Linux, etc.)?

**Comment by masen1991** [comment]
I also have this problem.
My platform info:
Linux version 2.6.32-431.23.3.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Wed Jul 16 06:12:23 EDT 2014

conda 4.9.2

**Comment by frequena** [comment]
Hello @jagathv,

Please find below my setup:

  conda 4.7.12
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-1062.12.1.el7.x86_64
  Architecture: x86-64

**Comment by jagathv** [comment]
@frequena @masen0407 Thanks for the information! 

We've exported a new environment config that should work for Linux - please pull the new changes, run `conda env create -f SVFXenv_all_platforms.yml && conda activate SVFXenv`, and let me know if errors persist.
